# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
app_identifier "com.tarappo.cisample"
username ENV["ITUNES_USER_NAME"]

release_notes({
  'en-US'   => "Sample Release Note",
  'default' => "Sample Release Note"
})

