fastlane_version "2.53.1"

default_platform :ios

platform :ios do

  lane :build do
    clean_build_artifacts

    gym(
      project: "ci-sample.xcodeproj",
      scheme: "ci-sample",
      configuration: "Release",
      export_method: "ad-hoc"
    )
  end

end
