default_platform :ios

platform :ios do
  keychain_name = "ios-build.keychain"
  keychain_password = SecureRandom.base64

 
  lane :build do
    clean_build_artifacts
    increment_build_number
    commit_version_bump(
      message: 'increment build number by fastlane',
      xcodeproj: 'ci-sample.xcodeproj',
      force: true
    )
    push_to_git_remote

    gym(
      project: "ci-sample.xcodeproj",
      scheme: "ci-sample",
      configuration: "Debug",
      export_method: "development"
    )
  end

  lane :build_adhoc do
    clean_build_artifacts
    increment_build_number
    commit_version_bump(
      message: 'increment build number by fastlane',
      xcodeproj: 'ci-sample.xcodeproj',
      force: true
    )
    push_to_git_remote

    gym(
      project: "ci-sample.xcodeproj",
      scheme: "ci-sample",
      configuration: "Release",
      export_method: "ad-hoc"
    )
  end

  lane :setup_certificate do
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    import_certificate(
      certificate_path: "travis/dist.p12",
      certificate_password: ENV["KEY_PASSWORD"],
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )
  end
end
